# Assignment-1

## Descriptive Statistics

__1. Import NumPy, SciPy, and Pandas__

In [9]:
import numpy as np
from scipy import stats 
import pandas as pd

__2. Randomly generate 1,000 samples from the normal distribution using np.random.normal()(mean = 100, standard deviation = 15)__

In [10]:
samples = np.random.normal(100, 15, 1000)



__3. Compute the mean, median, and mode__

In [11]:
mean = np.mean(samples)
print("samples_mean: ", mean)

median =np.median(samples)
print("samples_median: ", median)

mode = stats.mode(samples)
print("samples_mode: ", mode)

samples_mean:  99.69421057139178
samples_median:  99.77002400339197
samples_mode:  ModeResult(mode=array([53.62130672]), count=array([1]))


__4. Compute the min, max, Q1, Q3, and interquartile range__

In [12]:
minn = min(samples)
print("min_samples: ", minn)

maxx = max(samples)
print("max_samples: ", maxx)

q1 = np.percentile(samples, 25)
print("Q1_samples: ", q1)

q3 = np.percentile(samples, 75)
print("Q3_samples. ", q3)

iqr = stats.iqr(samples)
print("IQR_samples: ", iqr)

min_samples:  53.62130672057003
max_samples:  142.75626163236277
Q1_samples:  89.0157507732034
Q3_samples.  110.6236295548639
IQR_samples:  21.607878781660503


__5. Compute the variance and standard deviation__

In [13]:
variance = np.var(samples)
print("samples_variance: ", variance)

std_dev = np.std(samples)
print("samples_std_dev: ", std_dev)

samples_variance:  233.16756192858506
samples_std_dev:  15.269825209496835


__6. Compute the skewness and kurtosis__

In [14]:
from scipy.stats import kurtosis, skew
from scipy import stats

In [15]:
skewness = skew(samples)
print("samples_skewness: ", skewness)

kurtosis = kurtosis(samples)
print("samples_kurtosis: ", kurtosis)

samples_skewness:  -0.07625454368907053
samples_kurtosis:  -0.2582414129830948


## NumPy Correlation Calculation

__1. Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use np.arange()__

In [16]:
import numpy as np
from scipy import stats 
import pandas as pd

In [18]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

__2. Then use "np.array()" to create a second array y containing 10 arbitrary integers.__

In [19]:
y = np.random.randint(1, 30, 10)
y

array([ 1, 22, 29,  5, 11, 16,  7, 10, 24, 23])

__3. Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y__

In [21]:
r = np.corrcoef(x, y)
print(r)


[[1.         0.25043793]
 [0.25043793 1.        ]]


## Pandas Correlation Calculation

In [29]:
import pandas as pd

__1. Run the code below__

In [45]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [48]:
x

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [49]:
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

__2. Call the relevant method to calculate Pearson's r correlation.__

In [52]:
r = x.corr(y)
r

0.7586402890911867

__3. (OPTIONAL.) Call the relevant method to calculate Spearman's rho correlation.__

In [53]:
rho = x.corr(y, method='spearman')
rho

0.9757575757575757

## Seaborn Dataset Tips

__1. Import Seaborn Library__

In [54]:
import seaborn as sns

__2. Load "tips" dataset from Seaborn__

In [55]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [57]:
df = sns.load_dataset("tips")

In [58]:
df.head(10)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

__3. Generate descriptive statistics include those that summarize the central tendency, dispersion.__

In [59]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

__4. Call the relevant method to calculate pairwise Pearson's r correlation of columns.__

In [60]:
df.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000